### ISSUE TITLE
SyntaxError: Named export 'getDefaultCameraTransform' not found

### ISSUE THREAD

**Issue by anixan** [naver/egjs-flicking#805] opened 2023-05-22 12:23 UTC
## Description
I have a SvelteKit application that I have built and setup with this carousel, It runs fine in Dev however when come to run build i get the following errors and the build fails, I am not sure what is happening:

`import { getDefaultCameraTransform, range, withFlickingMethods } from "@egjs/flicking";
         ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'getDefaultCameraTransform' not found. The requested module '@egjs/flicking' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:`

Here is a copy of the imports on the +page.svelte:

`// Importing CSS styles
	import '../app.postcss';
	// Importing a Svelte component for QR code generation
    import QRCode from "$lib/qr.svelte";
	// Importing onMount from svelte for lifecycle hook
    import { onMount } from 'svelte';
    import '@splidejs/svelte-splide/css';
    import Flicking, { FlickingPanel } from "@egjs/svelte-flicking";
    //import { EVENTS } from "@egjs/flicking";
    import { Fade, Parallax, AutoPlay, Pagination } from "@egjs/flicking-plugins";
    import "@egjs/svelte-flicking/dist/flicking.css";`

## Steps to check or reproduce
I followed the instructions to install and use Flicking off the docs and am stumped here, hopefully someone can quickly help

**Comment by malangfox** [comment] 2023-05-30 06:10
Hello @anixan.

We have released @egjs/flicking 4.10.8-beta.0 and @egjs/svelte-flicking 4.10.8-beta.0 which fixes this issue.
Can you check if the issue you left is reproduced when using the above versions of the packages?

**Comment by malangfox** [comment] 2023-11-14 06:21
Since there is no further comment, we will close the issue.

**Closed by malangfox** 2023-11-14 06:21 UTC
Labels: :bookmark:4.x, :package:Svelte
