### ISSUE TITLE
Autoplay work only with first carousel

### ISSUE THREAD

**Issue by namanh6669** [naver/egjs-flicking#789] opened 2023-03-15 03:08 UTC
I have two instance egjs carousel but with plugin autoplay but only the first carousel work.
Framework Angular 15.
Can help me pls! Many Thanks

**Comment by malangfox** [comment] 2023-03-15 07:15
Hello @namanh6669.

I made a demo to reproduce this issue, but it did not reproduce the issue you left.
If there's somewhere you are likely to make a mistake in this implementation, you should declare a different Autoplay instance for each Flicking.

Is there an implementation we can check that is causing this issue?

**Comment by malangfox** [comment] 2023-11-14 06:23
Since there is no further comment, we will close the issue.

**Closed by malangfox** 2023-11-14 06:23 UTC
Labels: :electric_plug:Plugin, :package:Angular, :bookmark:4.x
