### ISSUE TITLE
Vue3/Typescript - updateAnimation does not extend duration if the animation is almost done

### ISSUE THREAD

**Issue by DriekSnellens** [naver/egjs-flicking#817] opened 2023-07-12 08:28 UTC
## Description

I have implemented navigation buttons hovering over the slider. When clicked multiple times I wanted the slider to move in one animation to the index after however many clicks the user has done. Example: user navigates with one click to index 0 to 1, then clicks 3 times during the animation, then the current animation must be extended while the carousel navigates to index 4.

When reading the documentation I thought https://naver.github.io/egjs-flicking/docs/api/Flicking#updateAnimation was the way to go. And this works! However, now if I navigate one slide, and click on the navigate button when the animation is almost done, I can see updateAnimation is called, but the animation duration is not extended. So it navigates instantly to the next slide. 

I use egjs/vue3-flicking 4.10.8

## Steps to check or reproduce
- Navigate to next slide ( moveTo function is called)
- Right when the animation is almost done, click on navigate next again
- animation is not extended and carousel navigates to the next slide within the duration of the current animation, so it navigates almost instantly

**Comment by malangfox** [comment] 2023-07-31 05:28
Hello @DriekSnellens.

We apologize for the delay in checking the issue you left.
We want to reproduce the issue you left, but we have a question about your implementation.

It won't be able to call `next` while `moveTo` executes. So can we check the repo or demo of how you identified this issue?

**Comment by malangfox** [comment] 2023-11-01 09:27
Since there is no further comment, we will close the issue.

**Closed by malangfox** 2023-11-01 09:27 UTC
Labels: :question:Question, :bookmark:4.x, :package:Vue3
